import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Indie Art App",
  description: "generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <header>
        
      </header>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
